export AWS_DATA_PATH="${HOME}/.aws"
export AWS_CONFIG_FILE="${AWS_DATA_PATH}/config"
export AWS_SHARED_CREDENTIALS_FILE="${AWS_DATA_PATH}/credentials"
export AWS_DEFAULT_REGION="us-east-1"
export AWS_DEFAULT_OUTPUT="json"
